vault_endpoints:
  gpx: http://vault.gpx.local:8200
  ntt: http://vault.ntt.local:8200

approle_defaults:
  token_ttl: "1h"
  token_max_ttl: "4h"
  secret_id_ttl: "24h"
  secret_id_num_uses: 10
  bind_secret_id: true
# vaultops/config/defaults.yaml
aws_assume_role_name: VaultAssumeTrustPolicyRole
